name: CI/CD Pipeline

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16'
            - name: Install dependencies
              run: npm install

    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16'
            - name: Install dependencies
              run: npm install
            - name: Run tests
              run: npm test

    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  # Github.com --> [My repository] --> Settings --> Secrets and Variables
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Echo DockerHub Username
              run: echo "Username is $DOCKERHUB_USERNAME"
              env:
                  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            - name: Build, tag, and push image to DockerHub
              run: |
                  docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME .
                  docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
              env:
                  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                  IMAGE_NAME: my-image
